default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: [-w=120]

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8 mvnet/ --indent-size=2 --select=F,E112,E113,E203,E304,E502,E702,E703,E71,E72,E731,W191,W6 --statistics -j4
        language: system
        always_run: true
        pass_filenames: false

      - id: mypy
        name: mypy
        entry: mypy mvnet/ --ignore-missing-imports --explicit-package-bases
        language: system
        always_run: true
        pass_filenames: false

      - id: pylint
        name: pylint
        entry: pylint --recursive=true mvnet/
        language: system
        always_run: true
        pass_filenames: false

      - id: pytest
        name: pytest
        entry: pytest test/
        language: system
        always_run: true
        pass_filenames: false
